### ISSUE TITLE
Problem in installing requirements

### ISSUE THREAD

**Issue by Gabri** [dream-overflow/siis#1]
Hello,

Just discovered this interesting project and I just wanted to test it.
When running
`pip install -r requirements.txt`
I get:
```
ERROR: Could not find a version that satisfies the requirement python-prctrl>=1.7 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for python-prctrl>=1.7 (from -r requirements.txt (line 1))
```
I tried to install the package manually:
`pip install python-prctl==1.7`
It worked (with sudo), but I get the error before again (in virtual env or not)...

Any ideas?

Another question: when you say, after `sudo make install`, to `copy the content of the include folder into siis.venv/include/ta-lib/ and copy the .a and .so to siis.venv/lib/pythonX.Y/site-packages` the files  are just `libta_lib.so` and `libta_lib.a`, right?

Thanks

**Comment by firebird631** [comment]
Hi Gabri, thanks for your report.

The package python-prctl is not mandatory, its only to have the ability to name the threads, its mainly for main developers. I will comment the python-prctrl>=1.7 line (add a # on the beginning of the line) and commit this soon (with another important fix for paper trader when using limits/stop orders).

For TA-Lib its libta_lib.a, libta_lib.so, libta_lib.so.0 and libta_lib.so.0.0.0. In my case I've copied them in /usr/local/lib directly and having export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH in my $HOME/.bashrc

Regards
