### ISSUE TITLE
issues after full installation

### ISSUE THREAD

**Issue by caressgents** [dream-overflow/siis#4]
After following step by step, your instructions, I am receiving the following errors, and can't for the life of me, figure out what I missed. Please see the following: 

`python3 siis.py
WARN: prctl module is not installed. You will not be able to see thread names
Starting SIIS using real identity...
- (Press 'q' twice to terminate)
- (Press 'h' for help)
- Using live-mode trader.
Starting monitor service...
- siis.monitor.desktopnotifier ModuleNotFoundError("No module named 'dbus'")
- siis.database.pgsql ModuleNotFoundError("No module named 'psycopg2'")
Traceback (most recent call last):
  File "siis.py", line 628, in <module>
    application(sys.argv)
  File "siis.py", line 294, in application
    Database.inst().setup(options)
  File "/home/toor/siis/database/database.py", line 161, in setup
    self.setup_market_sql()
  File "/home/toor/siis/database/pgsql.py", line 82, in setup_market_sql
    cursor = self._db.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'`

TIA

**Comment by caressgents** [comment]
@fredericlepied @firebird631

**Comment by firebird631** [comment]
Hi @caressgents did you install the requirements for postgresql client connector ? You have the file deps/reqspgsql.txt for that :

> pip install deps/reqspgsql.txt

Before you may need to install the libpq-dev package (or equiv on RH based distribution).

I've just made a commit with a more clean database error management. Thx for your report.

Tell me if you have another issue.

**Comment by caressgents** [comment]
installed the libpq-dev package, ran the requirements for postgresql, then tried running 'python siis.py' and received the following:

`python siis.py
WARN: prctl module is not installed. You will not be able to see thread names
Starting SIIS using real identity...
- (Input ':q<enter>' to terminate)
- (Input ':h<enter>' to display help)
- Using live-mode trader.
Starting monitor service...
- siis.monitor.desktopnotifier ModuleNotFoundError("No module named 'dbus'")
could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

Traceback (most recent call last):
  File "siis.py", line 333, in application
    Database.inst().setup(options)
  File "/home/toor/siis/database/database.py", line 162, in setup
    self.connect(config)
  File "/home/toor/siis/database/pgsql.py", line 72, in connect
    self._db = self.psycopg2.connect(self._conn_str)
  File "/home/toor/siis.venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "siis.py", line 689, in <module>
    application(sys.argv)
  File "siis.py", line 336, in application
    terminate(watcher_service, trader_service, strategy_service, monitor_service, desktop_service, view_service, notifier_service)
  File "siis.py", line 83, in terminate
    Database.terminate()
  File "/home/toor/siis/database/database.py", line 99, in terminate
    Database.__instance.close()
  File "/home/toor/siis/database/database.py", line 206, in close
    self._thread.join()
  File "/usr/lib/python3.7/threading.py", line 1027, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
`

@firebird631

**Comment by caressgents** [comment]
No matter what I do differently, I'm still getting errors, see the following; 

> ython siis.py real --profile=my-backtest1 --backtest --from=2018-08-01T00:00:00 --to=2018-12-31T23:59:59
WARN: prctl module is not installed. You will not be able to see thread names
Starting SIIS using real identity...
- (Input ':q<enter>' to terminate)
- (Input ':h<enter>' to display help)
Process a backtesting.
- Using paper-mode trader.
Starting monitor service...
- siis.monitor.desktopnotifier ModuleNotFoundError("No module named 'notify2'")
could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

Traceback (most recent call last):
  File "siis.py", line 333, in application
    Database.inst().setup(options)
  File "/home/toor/siis/database/database.py", line 162, in setup
    self.connect(config)
  File "/home/toor/siis/database/pgsql.py", line 72, in connect
    self._db = self.psycopg2.connect(self._conn_str)
  File "/home/toor/siis.venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "siis.py", line 689, in <module>
    application(sys.argv)
  File "siis.py", line 336, in application
    terminate(watcher_service, trader_service, strategy_service, monitor_service, desktop_service, view_service, notifier_service)
  File "siis.py", line 83, in terminate
    Database.terminate()
  File "/home/toor/siis/database/database.py", line 99, in terminate
    Database.__instance.close()
  File "/home/toor/siis/database/database.py", line 206, in close
    self._thread.join()
  File "/usr/lib/python3.7/threading.py", line 1027, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started


@firebird631

**Comment by firebird631** [comment]
You need to configure your PostgreSQL server correctly :

> Is the server running on host "127.0.0.1" and accepting
> TCP/IP connections on port 5432?

If you are using unix socket copy the config/database.json file into your $HOME/.siis/config/database.json and remove the "host" and "port" parameters,then restart.

**Comment by caressgents** [comment]
@firebird631 I thnk i'm going to just need to restart from the beginning.. I've found myself in a rabbit hole of errors at this point. 

I've got the postgresql server configured, and now running into this: 

> python siis.py
> WARN: prctl module is not installed. You will not be able to see thread names
> Starting SIIS using real identity...
> - (Input ':q<enter>' to terminate)
> - (Input ':h<enter>' to display help)
> - Using live-mode trader.
> Starting monitor service...
> - siis.monitor.desktopnotifier ModuleNotFoundError("No module named 'notify2'")
> FATAL:  password authentication failed for user "siis"
> FATAL:  password authentication failed for user "siis"
> 
> Traceback (most recent call last):
>   File "siis.py", line 333, in application
>     Database.inst().setup(options)
>   File "/home/toor/siis/database/database.py", line 162, in setup
>     self.connect(config)
>   File "/home/toor/siis/database/pgsql.py", line 72, in connect
>     self._db = self.psycopg2.connect(self._conn_str)
>   File "/home/toor/siis.venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: FATAL:  password authentication failed for user "siis"
> FATAL:  password authentication failed for user "siis"
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "siis.py", line 689, in <module>
>     application(sys.argv)
>   File "siis.py", line 336, in application
>     terminate(watcher_service, trader_service, strategy_service, monitor_service, desktop_service, view_service, notifier_service)
>   File "siis.py", line 83, in terminate
>     Database.terminate()
>   File "/home/toor/siis/database/database.py", line 99, in terminate
>     Database.__instance.close()
>   File "/home/toor/siis/database/database.py", line 206, in close
>     self._thread.join()
>   File "/usr/lib/python3.7/threading.py", line 1027, in join
>     raise RuntimeError("cannot join thread before it is started")
> RuntimeError: cannot join thread before it is started
> 

This is nuts, never had such a hard time with a set up install.. sorry for all of the Q's, but thank you for taking the time to help!

**Comment by caressgents** [comment]
I think I've gone full retard, LOL.

**Comment by firebird631** [comment]
Errors say you 

> FATAL: password authentication failed for user "siis"

Check how to configure a PostgreSQL server on tutorial, user permission, database creation... look at the sql/initpg.sql into the comment section it say : 

> -- $ psql -h localhost -U root -W -p 5432
> -- > CREATE DATABASE siis;
> -- > CREATE USER siis WITH ENCRYPTED PASSWORD 'siis';
> -- > GRANT ALL PRIVILEGES ON DATABASE siis TO siis;
> -- $ psql -h localhost -d siis -U siis -W -p 5432 -a -q -f initpg.sql

Or for a local unix socket : 

> -- $ psql -U root -W
> -- > CREATE DATABASE siis;
> -- > CREATE USER siis WITH ENCRYPTED PASSWORD 'siis';
> -- > GRANT ALL PRIVILEGES ON DATABASE siis TO siis;
> -- $ psql -d siis -U siis -W -a -q -f initpg.sql

**Comment by caressgents** [comment]
Man, I don't think it's meant to be. I've gone through each step meticulously so far, following the readme steps, and your guidance here. I'm still getting errors, including the above still w/ FATAL: password auth failed for user siis

@firebird631

**Comment by firebird631** [comment]
Yep but I cannot offer postgresql complete support. Maybe you have to edit your pg_hba.conf file to set md5, but please try to look postgresql tutorials.

**Comment by caressgents** [comment]
Understood, thanks anyways.
