### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by foxxcrypto** [dream-overflow/siis#6]
File "/home/luke_zinato/siis/terminal/terminal.py", line 13, in <module>
    import curses 
File "/usr/local/lib/python3.7/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

I have installed  all libncurses5 libncurses5-dev libncursesw5

Anyone could help?

**Comment by firebird631** [comment]
Which Python version did you use ? Need is 3.6 or greater. Or did you compile your own Python version ? Because default ./configure does not enable ssl neither curses modules ?
